[package]
name = "wheedle"
version = "0.1.0"
authors = ["Maciej Kula"]

[dependencies]
serde = { version = "1.0.24", features = ["rc"] }
serde_derive = "1.0.24"
csv = "1.0.0-beta.5"
bincode = "0.9.2"
rand = "0.3.18"
itertools = "0.7.3"
rayon = "0.9.0"
ndarray = { version = "0.10.13", features = ["serde-1"] }
derive_builder = "0.5.1"

wyrm = { path = "../wyrm" }

[profile.release]
lto = true

[profile.bench]
lto = true
debug = true
